const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.video,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Behaviors.Platform,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.solid,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Touch: 0},
	{Sprite2: 0},
	{Sprite5: 0},
	{Video: 0},
	{Sine: 0},
	{Text: 0},
	{Text2: 0},
	{Platform: 0},
	{Text3: 0},
	{DragDrop: 0},
	{Text4: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Solid: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Text5: 0},
	{Text6: 0},
	{Text7: 0},
	{Text8: 0},
	{Text9: 0},
	{Text10: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Text5: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	Text7: class extends self.ITextInstance {},
	Text8: class extends self.ITextInstance {},
	Text9: class extends self.ITextInstance {},
	Text10: class extends self.ITextInstance {}
}